version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - "5432:5432"
      # HEALTH CHECK CONDITION
    healthcheck:
#      test: ["CMD-SHELL", "pg_isready", "-U", "hello_django", "-h", "db"]
      test: "pg_isready -h db -U hello_django"
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
