version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn configuration.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - "5432:5432"
      # HEALTH CHECK CONDITION
    healthcheck:
      test: "pg_isready -h db -U hello_django"
      interval: 5s
      timeout: 5s
      retries: 3

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data: