---

# ============== UPDATING ==============
- hosts: all
  become: true
  pre_tasks:
    - name: install updates (CentOS)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

# ============== WEB SERVERS DEPENDENCIES ==============

- hosts: web_servers
  become: true
  tasks:
    - name: install apache2 and php package (CentOS)
      dnf:
        name:
         - httpd
         - php
      when: ansible_distribution == "CentOS"

    - name: install apache2 and php package (Ubuntu)
      apt:
        name:
          - apache2
          - libapache2-mod-php
      when: ansible_distribution == "Ubuntu"

# ============== DATABASE INSTALLATION ==============
- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package (CentOS)
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

# ============== FILE SERVERS INSTALLATION ==============
- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      package:
        name: samba
        state: latest
