# Generated by Django 4.2.4 on 2023-10-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_textlog_some_str_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="textlog",
            name="some_choices_field",
            field=models.CharField(
                choices=[
                    ("One", "One Million Dollars"),
                    ("Two", "Two Million Dollars"),
                    ("Three", "Three Million Dollars"),
                ],
                default="One",
                max_length=5,
            ),
        ),
    ]
